/*
DO AN MON HOC AN TOAN BAO MAT DU LIEU TRONG HTTT
    NHOM 10
    MSSV        HO TEN
    19127461    Tran Thi Thuy Linh
    19127521    Nguyen Thi Nhu Phuong
    19127544    Nguyen Hoan Hoai Tam
*/

--XOA TRUOC KHI TAO ( CHAY VOI VAI TRO SYS)
BEGIN
EXECUTE IMMEDIATE 'DROP USER QLYSCYT CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

--TAO USER QLYCSYT ( CHAY VOI VAI TRO SYS)
CREATE USER QLYCSYT IDENTIFIED BY 123;
GRANT ALL PRIVILEGE TO QLYCSYT;


-- XOA TAT CA CAC BANG TRUOC KHI TAO
DROP TABLE HSBA CASCADE CONSTRAINTS;
DROP TABLE HSBA_DV CASCADE CONSTRAINTS;
DROP TABLE BENHNHAN CASCADE CONSTRAINTS;
DROP TABLE CSYT CASCADE CONSTRAINTS;
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;

--TAO BANG
CREATE TABLE HSBA (
    MAHSBA VARCHAR2(10),
    MABN VARCHAR2(10),
    NGAY DATE,
    CHANDOAN VARCHAR2(100),
    MABS VARCHAR2(10),
    MAKHOA VARCHAR2(10),
    MACSYT VARCHAR2(10),
    KETLUAN VARCHAR2(100),
	CONSTRAINT PK_HSBA PRIMARY KEY ( MAHSBA )
);

CREATE TABLE HSBA_DV (
    MAHSBA VARCHAR2(10),
    MADV VARCHAR2(10),
    NGAY DATE,
    MAKTV VARCHAR2(10),
    KETQUA VARCHAR2(100),
	CONSTRAINT PK_HSBA_DV PRIMARY KEY ( MAHSBA, MADV, NGAY )
);


CREATE TABLE BENHNHAN (
	MABN VARCHAR2(10),
	MACSYT VARCHAR2(10),
	TENBN VARCHAR2(50),
	CMND CHAR(9),
	NGAYSINH DATE,
	SONHA INT,
	TENDUONG VARCHAR2(50),
	QUANHUYEN VARCHAR2(50),
	TINHTP VARCHAR2(50),
	TIENSUBENH VARCHAR2(100),
	TIENSUBENHGD VARCHAR2(100),
	DIUNGTHUOC VARCHAR2(100),
	CONSTRAINT PK_BENHNHAN PRIMARY KEY ( MABN )

);

CREATE TABLE CSYT(
	MACSYT VARCHAR2(10),
	TENCSYT VARCHAR2(50),
	DCCSYT VARCHAR2(100),
	SDTCSYT CHAR(10),
	CONSTRAINT PK_CSYT PRIMARY KEY ( MACSYT )
);

CREATE TABLE NHANVIEN(
	MANV VARCHAR2(10),
	HOTEN VARCHAR2(50),
	PHAI VARCHAR2(3) CHECK (PHAI IN(N'Nam',N'Nu')),
	NGAYSINH DATE,
	CMND CHAR(9),
	QUEQUAN VARCHAR2(50),
	SODT CHAR(10),
	CSYT VARCHAR2(10),
	VAITRO VARCHAR2(20) CHECK (VAITRO IN (N'Thanh tra', N'Co so y te', N'Y sy/bac sy', N'Nghien cuu')),
	CHUYENKHOA VARCHAR2(10),
	CONSTRAINT NHANVIEN_PK PRIMARY KEY ( MANV )
);

-- TAO CAC KHOA NGOAI
ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_BENHNHAN 
FOREIGN KEY ( MABN )
REFERENCES BENHNHAN ( MABN );

ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_NHANVIEN 
FOREIGN KEY ( MABS )
REFERENCES NHANVIEN ( MANV );

ALTER TABLE HSBA
ADD CONSTRAINT FK_HSBA_CSYT 
FOREIGN KEY ( MACSYT )
REFERENCES CSYT ( MACSYT);

ALTER TABLE HSBA_DV
ADD CONSTRAINT FK_HSBA_DV_HSBA 
FOREIGN KEY ( MAHSBA )
REFERENCES HSBA ( MAHSBA );

ALTER TABLE BENHNHAN
ADD CONSTRAINT FK_BENHNHAN_CSYT 
FOREIGN KEY ( MACSYT )
REFERENCES CSYT ( MACSYT);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_CSYT 
FOREIGN KEY ( CSYT )
REFERENCES CSYT ( MACSYT);


--TAO CAC THU TUC
CREATE OR REPLACE PROCEDURE  sp_THEMNHANVIEN(
    manv IN NHANVIEN.MANV%TYPE,
    hoten  IN NHANVIEN.HOTEN%TYPE,
    phai  IN NHANVIEN.PHAI%TYPE,
    ngaysinh  IN VARCHAR2,
    cmnd  IN NHANVIEN.CMND%TYPE,
    quequan  IN NHANVIEN.QUEQUAN%TYPE,
    sodt  IN NHANVIEN.SODT%TYPE,
    csyt  IN NHANVIEN.CSYT%TYPE,
    vaitro  IN NHANVIEN.VAITRO%TYPE,
    chuyenkhoa  IN NHANVIEN.CHUYENKHOA%TYPE)
AS
    strSQL VARCHAR2(200);
BEGIN
    INSERT INTO NHANVIEN ("MANV", "HOTEN", "PHAI","NGAYSINH","CMND","QUEQUAN", "SODT","CSYT", "VAITRO", "CHUYENKHOA") 
    VALUES (manv, hoten, phai,TO_DATE(ngaysinh,'yyyy-mm-dd'),cmnd ,quequan, sodt, csyt, vaitro, chuyenkhoa);
    strSQL :='CREATE USER "'||manv||'" IDENTIFIED BY "'||cmnd||'"';
    EXECUTE IMMEDIATE (strSQL);
    strSQL :='GRANT R_NHANVIEN TO "'||manv||'"';
    EXECUTE IMMEDIATE (strSQL);
END;

CREATE OR REPLACE PROCEDURE sp_THEMBENHNHAN(
    mabn BENHNHAN.MABN%TYPE,
    macsyt BENHNHAN.MACSYT%TYPE,
    tenbn BENHNHAN.TENBN%TYPE,
    cmnd BENHNHAN.CMND%TYPE,
    ngaysinh  VARCHAR2,
    sonha BENHNHAN.SONHA%TYPE,
    tenduong BENHNHAN.TENDUONG%TYPE,
    quanhuyen BENHNHAN.QUANHUYEN%TYPE,
    tinhtp BENHNHAN.TINHTP%TYPE,
    tiensubenh BENHNHAN.TIENSUBENH%TYPE,
    tiensubenhgd BENHNHAN.TIENSUBENHGD%TYPE,
    diungthuoc BENHNHAN.DIUNGTHUOC%TYPE)
AS
    strSQL VARCHAR2(200);
BEGIN
    INSERT INTO BENHNHAN ("MABN","MACSYT","TENBN","CMND","NGAYSINH","SONHA","TENDUONG","QUANHUYEN","TINHTP","TIENSUBENH","TIENSUBENHGD","DIUNGTHUOC")
    VALUES (mabn,macsyt,tenbn,cmnd,TO_DATE(ngaysinh,'yyyy-mm-dd'),sonha,tenduong,quanhuyen,tinhtp,tiensubenh,tiensubenhgd,diungthuoc);
    strSQL :='CREATE USER "'||mabn||'" IDENTIFIED BY "'||cmnd||'"';
    EXECUTE IMMEDIATE (strSQL);
    strSQL :='GRANT R_BENHNHAN TO "'||mabn||'"';
    EXECUTE IMMEDIATE (strSQL);
END;

