alter session set "_ORACLE_SCRIPT" = true;
ALTER SESSION SET CONTAINER = xepdb1;
--XOA TRUOC KHI TAO ( CHAY VOI VAI TRO SYS)
BEGIN
EXECUTE IMMEDIATE 'DROP USER QLYCSYT CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

--TAO USER QLYCSYT ( CHAY VOI VAI TRO SYS)
CREATE USER QLYCSYT IDENTIFIED BY "123";
GRANT DBA TO QLYCSYT;
GRANT CREATE SESSION TO QLYCSYT;
GRANT CREATE ANY CONTEXT, CREATE PROCEDURE TO QLYCSYT;
GRANT EXECUTE ON DBMS_SESSION TO QLYCSYT;

-- co the truy cap DBA_ROLE_PRIV trong function
GRANT SELECT ANY DICTIONARY TO QLYCSYT; 
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO QLYCSYT;
GRANT ALTER SESSION TO QLYCSYT;

--DBA them, cap nhat du lieu trong CSYT
GRANT INSERT ON CSYT TO QLYCSYT;
GRANT UPDATE ON CSYT TO QLYCSYT;

--DBA them du lieu trong NHANVIEN
GRANT INSERT ON NHANVIEN TO QLYCSYT;

--chay voi QLYCSYT
--tao role BENHNHAN
alter session set "_ORACLE_SCRIPT" = true;
ALTER SESSION SET CONTAINER = xepdb1;
CREATE ROLE R_BENHNHAN;

--tao user cho benh nhan
CREATE OR REPLACE PROCEDURE CreateUserBenhNhan
AS
    CURSOR cur IS (SELECT MABN
                   FROM BENHNHAN
                   WHERE MABN NOT IN (SELECT USERNAME FROM ALL_USERS));
    strSQL VARCHAR(300);
    usr VARCHAR2(30);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL := 'CREATE USER ' || Usr || ' IDENTIFIED BY ' || Usr;
        EXECUTE IMMEDIATE (strSQL);
        strSQL := 'GRANT CREATE SESSION TO ' || Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
END;

exec CreateUserBenhNhan;

--grant role cho user
DECLARE v_benhnhan BENHNHAN%ROWTYPE;
        strSQL VARCHAR2(200);
BEGIN
    FOR v_benhnhan IN(SELECT MABN FROM BENHNHAN)
    LOOP
        strSQL := 'GRANT R_BENHNHAN TO "'||v_benhnhan.MABN||'"';
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
END;

--tao user cho nhan vien
CREATE OR REPLACE PROCEDURE CreateUserNhanVien
AS
    CURSOR cur IS (SELECT MANV
                   FROM NHANVIEN
                   WHERE MANV NOT IN (SELECT USERNAME FROM ALL_USERS));
    strSQL VARCHAR(300);
    usr VARCHAR2(30);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO Usr;
        EXIT WHEN CUR%NOTFOUND;
        
        strSQL := 'CREATE USER ' || Usr || ' IDENTIFIED BY ' || Usr;
        EXECUTE IMMEDIATE (strSQL);
        strSQL := 'GRANT CREATE SESSION TO ' || Usr;
        EXECUTE IMMEDIATE (strSQL);
    END LOOP;
END;

exec CreateUserNhanVien;
