
--XOA TRUOC KHI TAO ( CHAY VOI VAI TRO SYS)
BEGIN
EXECUTE IMMEDIATE 'DROP USER QLYSCYT CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

--TAO USER QLYCSYT ( CHAY VOI VAI TRO SYS)
CREATE USER QLYCSYT IDENTIFIED BY 123;
GRANT ALL PRIVILEGE TO QLYCSYT;

-- CAP QUYEN DE CAI DAT MA HOA
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO QLYCSYT;

--CAP QUYEN SELECT TREN BANG 
GRANT SELECT ON DBA_AUDIT_TRAIL TO QLYCSYT;
