--TC#2
--TAO ROLE R_THANH TRA
CREATE ROLE R_THANHTRA ;

--CAP QUYEN CHO ROLE R_THANH TRA
GRANT SELECT ON HSBA TO R_THANHTRA;
GRANT SELECT ON HSBA_DV TO R_THANHTRA;
GRANT SELECT ON BENHNHAN TO R_THANHTRA;
GRANT SELECT ON CSYT TO R_THANHTRA;
GRANT SELECT ON NHANVIEN TO R_THANHTRA;
