--TC#2
--TAO ROLE THANH TRA
CREATE ROLE R_THANHTRA ;

--CAP QUYEN CHO ROLE THANH TRA
GRANT CREATE SESSION TO R_THANHTRA;
GRANT SELECT ON HSBA TO R_THANHTRA;
GRANT SELECT ON HSBA_DV TO R_THANHTRA;
GRANT SELECT ON BENHNHAN TO R_THANHTRA;
GRANT SELECT ON CSYT TO R_THANHTRA;
GRANT SELECT ON NHANVIEN TO R_THANHTRA;

--CAP ROLE THANH TRA CHO NHAN VIEN CO VAI TRO THANH TRA
DECLARE v_nhanvien NHANVIEN%ROWTYPE;
        strSQL VARCHAR2(200);
BEGIN
    FOR v_nhanvien IN(SELECT MANV,VAITRO FROM NHANVIEN)
    LOOP
        IF v_nhanvien.VAITRO = 'Thanh tra' THEN
            strSQL := 'GRANT R_THANHTRA TO "'||v_nhanvien.MANV||'"';
            EXECUTE IMMEDIATE (strSQL);
        END IF;
    END LOOP;
END;

