--TAO ROLE COSOYTE
CREATE ROLE R_COSOYTE;

--CAP QUYEN CHO ROLE R_COSOYTE
GRANT SELECT ON HSBA TO R_COSOYTE;
GRANT SELECT ON HSBA_DV TO R_COSOYTE;

--THIET LAP VPD CHO NV_COSOYTE THEM, XOA HSBA
CREATE OR REPLACE FUNCTION fn_CSYT_HSBA(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MACSYT = (SELECT CSYT FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLBV','HSBA','csyt_hsba','QLBV','fn_CSYT_HSBA','select,insert,delete');
/


