
--TC#4
--TAO ROLE R_YSI_BACSI
CREATE ROLE R_YSI_BACSI;

--CAP QUYEN CHO ROLE R_YSI_BACSI
GRANT SELECT ON BENHNHAN TO R_YSI_BACSI;


--THIET LAP VPD CHO Y SI BAC SI
CREATE OR REPLACE FUNCTION fn_YBS_HSBA(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MABS = (SELECT MANV FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
END;

EXEC DBMS_RLS.ADD_POLICY('QLCSYTE','HSBA','ybs_hsba','QLCSYTE','fn_YBS_HSBA','select');

CREATE OR REPLACE FUNCTION fn_YBS_HSBA_DV(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MAHSBA IN (SELECT MAHSBA FROM HSBA WHERE MABS = (SELECT MANV FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')))';
END;

EXEC DBMS_RLS.ADD_POLICY('QLCSYTE','HSBA_DV','ybs_hsba_dv','QLCSYTE','fn_YBS_HSBA_DV','select');
