
--TC#4
--TAO ROLE R_YSI_BACSI
CREATE ROLE R_YSI_BACSI;


--TAO VIEW
CREATE OR REPLACE VIEW V_YSIBACSI_HSBA
AS SELECT * 
FROM HSBA
WHERE MABS =SYS_CONTEXT('userenv', 'session_user');
        
CREATE OR REPLACE VIEW V_YSIBACSI_HSBA_DV
AS SELECT *
FROM HSBA_DV
WHERE MAHSBA IN(SELECT MAHSBA FROM V_YSIBACSI_HSBA);

--CAP QUYEN CHO ROLE R_YSI_BACSI
GRANT SELECT ON BENHNHAN TO R_YSI_BACSI;
GRANT SELECT ON V_YSIBACSI_HSBA TO R_YSI_BACSI;
GRANT SELECT ON V_YSIBACSI_HSBA_DV TO R_YSI_BACSI;
