
--TC#4
--TAO ROLE R_YSY_BACSY
CREATE ROLE R_YSY_BACSY;

--CAP QUYEN CHO ROLE R_YSY_BACSY
GRANT CREATE SESSION TO R_YSY_BACSY;
GRANT SELECT ON BENHNHAN TO R_YSY_BACSY;

--CAP R_YSY_BACSY CHO NHAN VIEN CO VAI TRO Y SY BAC SI
DECLARE v_nhanvien NHANVIEN%ROWTYPE;
        strSQL VARCHAR2(200);
BEGIN
    FOR v_nhanvien IN(SELECT MANV,VAITRO FROM NHANVIEN)
    LOOP
        IF v_nhanvien.VAITRO = 'Y sy/bac sy' THEN
            strSQL := 'GRANT R_YSY/BACSY TO "'||v_nhanvien.MANV||'"';
            EXECUTE IMMEDIATE (strSQL);
        END IF;
    END LOOP;
END;

--THIET LAP VPD CHO Y SY BAC SY
CREATE OR REPLACE FUNCTION fn_YBS_HSBA(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MABS = (SELECT MANV FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
END;

EXEC DBMS_RLS.ADD_POLICY('QLCSYTE','HSBA','ybs_hsba','QLCSYTE','fn_YBS_SEL_HSBA','select');

CREATE OR REPLACE FUNCTION fn_YBS_HSBA_DV(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MAHSBA IN (SELECT MAHSBA FROM HSBA WHERE MABS = (SELECT MANV FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')))';
END;

EXEC DBMS_RLS.ADD_POLICY('QLCSYTE','HSBA_DV','ybs_hsba_dv','QLCSYTE','fn_YBS_HSBA_DV','select');