
--TC5
--TAO ROLE R_NGHIENCUU
CREATE ROLE R_NGHIENCUU;

--TAO VIEW
CREATE OR REPLACE VIEW V_NGHIENCUU_HSBA
AS SELECT * 
FROM HSBA
WHERE MACSYT =(SELECT CSYT FROM NHANVIEN WHERE MANV = SYS_CONTEXT('userenv', 'session_user'))
        AND MAKHOA =(SELECT CHUYENKHOA FROM NHANVIEN WHERE MANV = SYS_CONTEXT('userenv', 'session_user'));
        
CREATE OR REPLACE VIEW V_NGHIENCUU_HSBA_DV
AS SELECT *
FROM HSBA_DV
WHERE MAHSBA IN(SELECT MAHSBA FROM V_NGHIENCUU_HSBA);

--CAP QUYEN CHO ROLE R_NGHIENCUU
GRANT SELECT ON V_NGHIENCUU_HSBA TO R_NGHIENCUU;
GRANT SELECT ON V_NGHIENCUU_HSBA_DV TO R_NGHIENCUU;
