
--TC#6
--TAO ROLE NHANVIEN , BENH NHAN
CREATE ROLE R_NHANVIEN;
CREATE ROLE R_BENHNHAN;

--TAO VIEW
CREATE OR REPLACE VIEW V_NHANVIEN_THONGTINCANHAN
AS SELECT *
FROM NHANVIEN
WHERE MANV = SYS_CONTEXT('userenv', 'session_user')
WITH CHECK OPTION;

CREATE OR REPLACE VIEW V_BENHNHAN_THONGTINCANHAN
AS 
SELECT * FROM BENHNHAN
WHERE MABN = SYS_CONTEXT('userenv', 'session_user')
WITH CHECK OPTION;

--CAP QUYEN CHO ROLE R_NHANVIEN
GRANT CREATE SESSION TO R_NHANVIEN;
GRANT SELECT ON V_NHANVIEN_THONGTINCANHAN TO R_NHANVIEN;
GRANT UPDATE (HOTEN, PHAI, SODT, NGAYSINH, QUEQUAN, CMND, CSYT, VAITRO, CHUYENKHOA) ON V_NHANVIEN_THONGTINCANHAN TO R_NHANVIEN;
--CAP QUYEN CHO ROLE R_BENHNHAN
GRANT CREATE SESSION TO R_BENHNHAN;
GRANT SELECT ON V_BENHNHAN_THONGTINCANHAN TO R_BENHNHAN;
GRANT UPDATE (MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON V_BENHNHAN_THONGTINCANHAN TO R_BENHNHAN;

--TAO TRIGGER CAP NHAT THONG TIN NHANVIEN & BENHNHAN
--NHAN VIEN 
CREATE OR REPLACE TRIGGER TRG_UPDATE_NHANVIEN
INSTEAD OF UPDATE ON QLYCSYT.V_NHANVIEN_THONGTINCANHAN
FOR EACH ROW
DECLARE
BEGIN
    UPDATE NHANVIEN 
    SET HOTEN = :NEW.HOTEN, 
        PHAI = :NEW.PHAI, 
        SODT = :NEW.SODT, 
        NGAYSINH = :NEW.NGAYSINH, 
        QUEQUAN = :NEW.QUEQUAN,
        CMND = :NEW.CMND,
        CSYT = :NEW.CSYT, 
        VAITRO = :NEW.VAITRO,
        CHUYENKHOA = :NEW.CHUYENKHOA
    WHERE MANV = :NEW.MANV;
END ;

--BENH NHAN
CREATE OR REPLACE TRIGGER TRG_UPDATE_BENHNHAN
INSTEAD OF UPDATE ON QLYCSYT.V_BENHNHAN_THONGTINCANHAN
FOR EACH ROW
DECLARE
BEGIN
    UPDATE BENHNHAN 
    SET MACSYT = :NEW.MACSYT, 
        TENBN = :NEW.TENBN, 
        CMND = :NEW.CMND,         
        NGAYSINH = :NEW.NGAYSINH,
        SONHA = :NEW.SONHA,
        TENDUONG = :NEW.TENDUONG, 
        QUANHUYEN = :NEW.QUANHUYEN, 
        TINHTP = :NEW.TINHTP, 
        TIENSUBENH = :NEW.TIENSUBENH, 
        TIENSUBENHGD = :NEW.TIENSUBENHGD, 
        DIUNGTHUOC = :NEW.DIUNGTHUOC
    WHERE MABN = :NEW.MABN;
END ;

