
--TC#6
--TAO ROLE NHANVIEN , BENH NHAN
CREATE ROLE R_NHANVIEN;
CREATE ROLE R_BENHNHAN;

--TAO VIEW
CREATE OR REPLACE VIEW V_NHANVIEN_THONGTINCANHAN
AS SELECT *
FROM NHANVIEN
WHERE MANV = SYS_CONTEXT('userenv', 'session_user')
WITH CHECK OPTION;

CREATE OR REPLACE VIEW V_BENHNHAN_THONGTINCANHAN
AS 
SELECT * FROM BENHNHAN
WHERE MANV = SYS_CONTEXT('userenv', 'session_user')
WITH CHECK OPTION;

--CAP QUYEN CHO ROLE R_NHANVIEN
GRANT CREATE SESSION TO R_NHANVIEN;
GRANT SELECT ON V_NHANVIEN_THONGTINCANHAN TO R_NHANVIEN;
GRANT UPDATE (HOTEN, PHAI, SODT, NGAYSINH, QUEQUAN, CMND, CSYT, VAITRO, CHUYENKHOA) ON V_NHANVIEN_THONGTINCANHAN TO R_NHANVIEN;
--CAP QUYEN CHO ROLE R_BENHNHAN
GRANT CREATE SESSION TO R_BENHNHAN;
GRANT SELECT ON V_BENHNHAN_THONGTINCANHAN TO R_BENHNHAN;
GRANT UPDATE (MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON V_BENHNHAN_THONGTINCANHAN TO R_BENHNHAN;

